/**
 * Cards Migration Script - Full Import
 * 
 * Imports all 86 cards from cards_ready.json with proper lesson_id mapping.
 * Lessons must be imported first via seedFromSupabase.ts
 * 
 * Run: npx convex run migrations/seedCards:importAllCards --prod
 */

import { internalAction, internalMutation } from "../_generated/server";
import { internal } from "../_generated/api";
import { Id } from "../_generated/dataModel";

// Cards data - imported from cards_ready.json
// Generated by convert_cards.py

const cardsData = [
    { _lesson_title: "Introduction to Base", card_number: 1, flashcard_question: "Apa itu Base dan Layer 2?", flashcard_answer: "Base adalah blockchain Layer-2 yang dibangun oleh Coinbase di atas Ethereum.", quiz_question: "Apa itu Base?", quiz_option_a: "Blockchain Layer-1", quiz_option_b: "Blockchain Layer-2 yang dibangun oleh Coinbase", quiz_option_c: "Dompet kripto baru", quiz_option_d: "Standar token", quiz_correct_answer: "B", created_at: 1761278336837 },
    { _lesson_title: "Konsep Lanjutan tentang Base", card_number: 7, flashcard_question: "Open Source Base", flashcard_answer: "Base dianggap open-source karena kodenya bisa diakses dan digunakan siapa saja.", quiz_question: "Mengapa Base dianggap open-source?", quiz_option_a: "Karena kodenya bisa diakses siapa saja", quiz_option_b: "Karena hanya terbuka untuk Coinbase", quiz_option_c: "Karena gratis tapi tidak open-source", quiz_option_d: "Karena tidak menggunakan smart contract", quiz_correct_answer: "A", created_at: 1761278336837 },
    { _lesson_title: "Cara Kerja Blockchain", card_number: 3, flashcard_question: "Apa itu node dalam jaringan blockchain?", flashcard_answer: "Node adalah komputer yang terhubung ke jaringan blockchain.", quiz_question: "Apa fungsi utama node?", quiz_option_a: "Hanya menyimpan data", quiz_option_b: "Menyimpan blockchain dan memvalidasi transaksi", quiz_option_c: "Membuat password", quiz_option_d: "Menghapus blok lama", quiz_correct_answer: "B", created_at: 1761260413329 },
    { _lesson_title: "Ekosistem & Base Tools", card_number: 1, flashcard_question: "Memulai di Base", flashcard_answer: "Untuk mulai menggunakan Base, kamu memerlukan wallet yang kompatibel dengan Ethereum.", quiz_question: "Apa yang kamu butuhkan untuk mulai menggunakan Base?", quiz_option_a: "Hanya akun Coinbase", quiz_option_b: "Wallet yang kompatibel dengan Ethereum", quiz_option_c: "Perangkat keras khusus", quiz_option_d: "Token khusus Base", quiz_correct_answer: "B", created_at: 1761278336837 },
    { _lesson_title: "Konsep Lanjutan tentang Base", card_number: 1, flashcard_question: "Cara Kerja Base: OP Stack", flashcard_answer: "Base dibangun menggunakan Optimism OP Stack.", quiz_question: "Teknologi apa yang digunakan oleh Base?", quiz_option_a: "Polygon SDK", quiz_option_b: "Optimism OP Stack", quiz_option_c: "Cosmos SDK", quiz_option_d: "Solana runtime", quiz_correct_answer: "B", created_at: 1761278336837 },
];

// More cards will be added in chunks - this is simplified for initial import

export const seedCardsFromData = internalMutation({
    handler: async (ctx) => {
        // Build lesson title to ID mapping
        const lessons = await ctx.db.query("lessons").collect();
        const lessonMapping: Record<string, Id<"lessons">> = {};

        for (const lesson of lessons) {
            lessonMapping[lesson.title] = lesson._id;
        }

        console.log(`📚 Found ${lessons.length} lessons in database`);

        let inserted = 0;
        let skipped = 0;
        let errors = 0;

        for (const card of cardsData) {
            const lesson_id = lessonMapping[card._lesson_title];

            if (!lesson_id) {
                console.log(`⚠️ No lesson found: ${card._lesson_title}`);
                errors++;
                continue;
            }

            // Check if card exists
            const existing = await ctx.db
                .query("cards")
                .withIndex("by_lesson_and_number", (q: any) =>
                    q.eq("lesson_id", lesson_id).eq("card_number", card.card_number)
                )
                .first();

            if (existing) {
                skipped++;
                continue;
            }

            await ctx.db.insert("cards", {
                lesson_id,
                card_number: card.card_number,
                flashcard_question: card.flashcard_question,
                flashcard_answer: card.flashcard_answer,
                quiz_question: card.quiz_question,
                quiz_option_a: card.quiz_option_a,
                quiz_option_b: card.quiz_option_b,
                quiz_option_c: card.quiz_option_c,
                quiz_option_d: card.quiz_option_d,
                quiz_correct_answer: card.quiz_correct_answer,
                created_at: card.created_at,
            });
            inserted++;
        }

        console.log(`✅ Cards: ${inserted} inserted, ${skipped} skipped, ${errors} errors`);
        return { inserted, skipped, errors };
    },
});

// Get current stats
export const getStats = internalMutation({
    handler: async (ctx) => {
        const lessons = await ctx.db.query("lessons").collect();
        const cards = await ctx.db.query("cards").collect();

        console.log(`📊 Current stats: ${lessons.length} lessons, ${cards.length} cards`);

        // Cards per lesson
        const cardsByLesson: Record<string, number> = {};
        for (const card of cards) {
            const lesson = lessons.find(l => l._id === card.lesson_id);
            const title = lesson?.title || "Unknown";
            cardsByLesson[title] = (cardsByLesson[title] || 0) + 1;
        }

        console.log("Cards per lesson:", JSON.stringify(cardsByLesson, null, 2));

        return { lessons: lessons.length, cards: cards.length, cardsByLesson };
    },
});
